main:
- name: Arts
  pageRef: /arts
  weight: 10
- name: Life
  pageRef: /life
  weight: 20
- name: Tech
  pageRef: /tech
  weight: 30
  
legal:
- name: About
  pageRef: /legal/about
  weight: 10
- name: Credits
  pageRef: /legal/credits
  weight: 20
- name: Privacy Policy
  pageRef: /legal/privacy
  weight: 30
- name: Terms of Use
  pageRef: /legal/terms
  weight: 40