canonicalBaseURL: https://www.haiverin.scot/

author:
  name: John Urquhart Ferguson
  email: enquiries@haiverin.scot
  post: Haiverin, PO Box 10101, Glasgow, G71 9DN, UK

description: A Scot shouting nonsense into the void.
images:
- /social-logo.svg
social:
  facebook_admin: john.u.ferguson

enableSearch: true
searchPagerSize: 5

logo:
  svg: "images/logo.svg"
  height: "3.75rem"
  width: "3.75rem"

colors:  # Standard Theme
  logoHigh: "#15C5FE"
  logoLow: "#A100FA"
  siteBackground: "#F9F9F9"
  boxBackground: "#F9F9F9"
  navA: "#7C8C8C"
  navAActive: "#0B0D0C"
  navAHover: "#5C6C6C"
  a: "#7C8C8C"
  aActive: "#0B0D0C"
  aHover: "#5C6C6C"
  bodyText: "#0B0D0C"
  h1: "#0B0D0C"
  summary: "#5C6C6C"
  logoHighDark: "#15C5FE"
  logoLowDark: "#A100FA"
  siteBackgroundDark: "#06151A"
  boxBackgroundDark: "#061E26"
  navADark: "#7C8C8C"
  navAActiveDark: "#F9F9F9"
  navAHoverDark: "#5C6C6C"
  aDark: "#7C8C8C"
  aActiveDark: "#F9F9F9"
  aHoverDark: "#5C6C6C"
  bodyTextDark: "#F9F9F9"
  h1Dark: "#F9F9F9"
  summaryDark: "#7562AD"


dateColors:  # Seasonal Themes (cannot span across the yearline). startDate is first active day. endDate is last active day. Both are MM-DD formatted.
- name: Halloween
  startDate: 10-01
  endDate: 10-31
  logoHigh: "#FC8B02"
  logoLow: "#A100FA"
  siteBackground: "#F9F9F9"
  boxBackground: "#F9F9F9"
  navA: "#7C8C8C"
  navAActive: "#0B0D0C"
  navAHover: "#5C6C6C"
  a: "#7C8C8C"
  aActive: "#0B0D0C"
  aHover: "#5C6C6C"
  bodyText: "#0B0D0C"
  h1: "#0B0D0C"
  summary: "#7562AD"
  logoHighDark: "#FC8B02"
  logoLowDark: "#A100FA"
  siteBackgroundDark: "#0C030C"
  boxBackgroundDark: "#160416"
  navADark: "#7C8C8C"
  navAActiveDark: "#F9F9F9"
  navAHoverDark: "#5C6C6C"
  aDark: "#7C8C8C"
  aActiveDark: "#F9F9F9"
  aHoverDark: "#5C6C6C"
  bodyTextDark: "#F9F9F9"
  h1Dark: "#F9F9F9"
  summaryDark: "#7562AD"

- name: Easter
  startDate: 03-15
  endDate: 04-25
  logoHigh: "#6DDCFF"
  logoLow: "#D66D82"
  siteBackground: "#FFFFFC"
  boxBackground: "#FCFEFF"
  navA: "#7C8C8C"
  navAActive: "#0B0D0C"
  navAHover: "#5C6C6C"
  a: "#7C8C8C"
  aActive: "#0B0D0C"
  aHover: "#5C6C6C"
  bodyText: "#0B0D0C"
  h1: "#0B0D0C"
  summary: "#93B39F"
  logoHighDark: "#6DDCFF"
  logoLowDark: "#D66D82"
  siteBackgroundDark: "#1A1A0D"
  boxBackgroundDark: "#0D1A19"
  navADark: "#7C8C8C"
  navAActiveDark: "#F9F9F9"
  navAHoverDark: "#5C6C6C"
  aDark: "#7C8C8C"
  aActiveDark: "#F9F9F9"
  aHoverDark: "#5C6C6C"
  bodyTextDark: "#F9F9F9"
  h1Dark: "#F9F9F9"
  summaryDark: "#93B39F"

- name: Christmas
  startDate: 12-01
  endDate: 12-31
  logoHigh: "#08A64F"
  logoLow: "#BD291B"
  siteBackground: "#FCFEFF"
  boxBackground: "#FDFFFC"
  navA: "#7C8C8C"
  navAActive: "#0B0D0C"
  navAHover: "#5C6C6C"
  a: "#7C8C8C"
  aActive: "#0B0D0C"
  aHover: "#5C6C6C"
  bodyText: "#0B0D0C"
  h1: "#0B0D0C"
  summary: "#9A1D36"
  logoHighDark: "#08A64F"
  logoLowDark: "#BD291B"
  siteBackgroundDark: "#0D151A"
  boxBackgroundDark: "#181A17"
  navADark: "#7C8C8C"
  navAActiveDark: "#F9F9F9"
  navAHoverDark: "#5C6C6C"
  aDark: "#7C8C8C"
  aActiveDark: "#F9F9F9"
  aHoverDark: "#5C6C6C"
  bodyTextDark: "#F9F9F9"
  h1Dark: "#F9F9F9"
  summaryDark: "#9A1D36"

- name: New Year   # Duplicate of Christmas theme to work across yearline
  startDate: 01-01
  endDate: 01-05
  logoHigh: "#08A64F"
  logoLow: "#BD291B"
  siteBackground: "#FCFEFF"
  boxBackground: "#FDFFFC"
  navA: "#7C8C8C"
  navAActive: "#0B0D0C"
  navAHover: "#5C6C6C"
  a: "#7C8C8C"
  aActive: "#0B0D0C"
  aHover: "#5C6C6C"
  bodyText: "#0B0D0C"
  h1: "#0B0D0C"
  summary: "#9A1D36"
  logoHighDark: "#08A64F"
  logoLowDark: "#BD291B"
  siteBackgroundDark: "#0D151A"
  boxBackgroundDark: "#181A17"
  navADark: "#7C8C8C"
  navAActiveDark: "#F9F9F9"
  navAHoverDark: "#5C6C6C"
  aDark: "#7C8C8C"
  aActiveDark: "#F9F9F9"
  aHoverDark: "#5C6C6C"
  bodyTextDark: "#F9F9F9"
  h1Dark: "#F9F9F9"
  summaryDark: "#9A1D36"

- name: Summer
  startDate: 07-01
  endDate: 07-22
  logoHigh: "#FDFEFE"
  logoLow: "#1DBBBB"
  siteBackground: "#05794B"
  boxBackground: "#5B3A8A"
  navA: "#FDFEFE"
  navAActive: "#1F004B"
  navAHover: "#B0BABA"
  a: "#5B3A8A"
  aActive: "#5B3A8A"
  aHover: "#5B3A8A"
  bodyText: "#FDFEFE"
  h1: "#FDFEFE"
  summary: "#CBBDDF"
  logoHighDark: "#5B3A8A"
  logoLowDark: "#05794B"
  siteBackgroundDark: "#06151A"
  boxBackgroundDark: "#061E26"
  navADark: "#7C8C8C"
  navAActiveDark: "#FDFEFE"
  navAHoverDark: "#5C6C6C"
  aDark: "#7C8C8C"
  aActiveDark: "#FDFEFE"
  aHoverDark: "#5C6C6C"
  bodyTextDark: "#FDFEFE"
  h1Dark: "#FDFEFE"
  summaryDark: "#7562AD"


authors:
- name: John Urquhart Ferguson
  image: "images/Author - John Urquhart Ferguson.png"
  bio: "Overly enthusiastic teachers planted the seed of writing in John's mind by making him feel that he was somewhat more talented than he actually was. This drastic overestimation (mixed with misguided encouragement) led John to pursue the creation of new worlds in the hope of meeting their expectations.\n\n

John enjoys programming software that only he is likely to use, keeping an eye out for puffins, and whistling better than one would reasonably expect.\n\n

John's thoughts are often existential (and very occasionally clever), but he writes with a warmness that will melt your heart."
#  vcard: "BEGIN:VCARD\nVERSION:2.1\nN;CHARSET=UTF-8:Ferguson;John;Urquhart;Dr;PhD\nFN;CHARSET=UTF-8:John Urquhart Ferguson, PhD\nORG;CHARSET=UTF-8:Haiverin.scot\nTITLE;CHARSET=UTF-8:Webmaster\nEMAIL;TYPE=HOME:mail@johnurquhartferguson.info\nURL;TITLE:https://www.johnurquhartferguson.info\nEND:VCARD"
  website: https://johnurquhartferguson.info
  instagram: sympodius
  facebook: john.u.ferguson
  xtwitter: sympodius
  github: sympodius
  reddit: sympodius
  flickr: fictionality
  imvdb: john-ferguson
  email: mail@johnurquhartferguson.info
  keybase: sympodius
  
