author:
  name: John Urquhart Ferguson
  email: enquiries@haiverin.scot
  post: Haiverin, PO Box 10101, Glasgow, G71 9DN, UK

description: A Scot shouting nonsense into the void.
images:
- /social-logo.svg
social:
  facebook_admin: john.u.ferguson
    
enableSearch: true
searchPagerSize: 5

logo:
  svg: "images/logo.svg"
  height: "3.75rem"
  width: "3.75rem"

# colors:  # Normal
#  logoHigh: "#15C5FE"
#  logoLow: "#A100FA"
#  siteBackground: "#F9F9F9"
#  boxBackground: "#F9F9F9"
#  navA: "#7C8C8C"
#  navAActive: "#0B0D0C"
#  navAHover: "#5C6C6C"
#  a: "#7C8C8C"
#  aActive: "#0B0D0C"
#  aHover: "#5C6C6C"
#  bodyText: "#0B0D0C"
#  h1: "#0B0D0C"
#  summary: "#5C6C6C"

colors:  # Halloween
  logoHigh: "#FC8B02"
  logoLow: "#A100FA"
  siteBackground: "#0B0D0C"
  boxBackground: "#220723"
  navA: "#7C8C8C"
  navAActive: "#F9F9F9"
  navAHover: "#5C6C6C"
  a: "#7C8C8C"
  aActive: "#F9F9F9"
  aHover: "#5C6C6C"
  bodyText: "#F9F9F9"
  h1: "#F9F9F9"
  summary: "#1A8E00"

authors:
- name: John Urquhart Ferguson
  image: "images/Author - John Urquhart Ferguson.png"
  bio: "Overly enthusiastic teachers planted the seed of writing in John's mind by making him feel that he was somewhat more talented than he actually was. This drastic overestimation (mixed with misguided encouragement) led John to pursue the creation of new worlds in the hope of meeting their expectations.\n\n

John enjoys programming software that only he is likely to use, keeping an eye out for puffins, and whistling better than one would reasonably expect.\n\n

John's thoughts are often existential (and very occasionally clever), but he writes with a warmness that will melt your heart."
  website: https://johnurquhartferguson.info
  instagram: sympodius
  facebook: john.u.ferguson
  xtwitter: sympodius
  github: sympodius
  reddit: sympodius
  flickr: fictionality
  imvdb: john-ferguson
  email: mail@johnurquhartferguson.info
  keybase: sympodius
  